import Head from 'next/head'
import Menu from '../components/menu';
import Layout from '../components/layout';
import Main from '../components/main';
export default function Home() {
  return (

    <Layout>
      <Head>
        <title>API Deslocamento</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Main />
    </Layout>
  )
}
